### ISSUE TITLE
Copy images to build folder

### ISSUE THREAD

**Issue by peduarte** [jxnblk/mdx-go#23]
Hey,

I used `mdx-go` to spin up my personal site, using my repo's `README` as the content. The same as you did for yours!

I love the simplicity and how easy it is to maintain. Thanks for that!

I was wondering, is there a way to copy images from `src` to `dist`? 

I imagine if instead of using `mdx-go` I used `mdx` with the `webpack` loader I could do this,  but I love how tooling-less `mdx-go` is.

Thanks! 👊

**Comment by jxnblk** [comment]
I imagine you could either use an npm script with `cp` or something like https://github.com/webpack-contrib/copy-webpack-plugin for now, but not sure how it should work as a built-in feature for mdx-go

**Comment by peduarte** [comment]
Fair enough, makes sense. 

Yeah I might go with `cp`.

Cheers 👊

**Comment by peduarte** [comment]
For anyone interested, here's what I did:
https://github.com/peduarte/ped.ro/blob/master/package.json#L11

**Comment by atav1k** [comment]
Thanks @peduarte
